#############################################################################
# Makefile for building: esmu
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 1? 25 23:27:56 2021
# Project:  esmu.pro
# Template: subdirs
# Command: /usr/local/Trolltech/qt.x86.4.8.6/bin/qmake -o Makefile esmu.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/Trolltech/qt.x86.4.8.6/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub--home-hongtao-100ask-scada-src-scada-pro \
		sub--home-hongtao-100ask-scada-called-main-pro \
		sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro \
		sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro \
		sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro

src/$(MAKEFILE).scada: 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/hongtao/100ask/scada/src/scada.pro -o $(MAKEFILE).scada
sub--home-hongtao-100ask-scada-src-scada-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/hongtao/100ask/scada/src/scada.pro -o $(MAKEFILE).scada
sub--home-hongtao-100ask-scada-src-scada-pro: src/$(MAKEFILE).scada FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).scada
sub--home-hongtao-100ask-scada-src-scada-pro-make_default: src/$(MAKEFILE).scada FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).scada 
sub--home-hongtao-100ask-scada-src-scada-pro-make_first: src/$(MAKEFILE).scada FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).scada first
sub--home-hongtao-100ask-scada-src-scada-pro-all: src/$(MAKEFILE).scada FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).scada all
sub--home-hongtao-100ask-scada-src-scada-pro-clean: src/$(MAKEFILE).scada FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).scada clean
sub--home-hongtao-100ask-scada-src-scada-pro-distclean: src/$(MAKEFILE).scada FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).scada distclean
sub--home-hongtao-100ask-scada-src-scada-pro-install_subtargets: src/$(MAKEFILE).scada FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).scada install
sub--home-hongtao-100ask-scada-src-scada-pro-uninstall_subtargets: src/$(MAKEFILE).scada FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).scada uninstall
called/$(MAKEFILE).main: 
	@$(CHK_DIR_EXISTS) called/ || $(MKDIR) called/ 
	cd called/ && $(QMAKE) /home/hongtao/100ask/scada/called/main.pro -o $(MAKEFILE).main
sub--home-hongtao-100ask-scada-called-main-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) called/ || $(MKDIR) called/ 
	cd called/ && $(QMAKE) /home/hongtao/100ask/scada/called/main.pro -o $(MAKEFILE).main
sub--home-hongtao-100ask-scada-called-main-pro: called/$(MAKEFILE).main FORCE
	cd called/ && $(MAKE) -f $(MAKEFILE).main
sub--home-hongtao-100ask-scada-called-main-pro-make_default: called/$(MAKEFILE).main FORCE
	cd called/ && $(MAKE) -f $(MAKEFILE).main 
sub--home-hongtao-100ask-scada-called-main-pro-make_first: called/$(MAKEFILE).main FORCE
	cd called/ && $(MAKE) -f $(MAKEFILE).main first
sub--home-hongtao-100ask-scada-called-main-pro-all: called/$(MAKEFILE).main FORCE
	cd called/ && $(MAKE) -f $(MAKEFILE).main all
sub--home-hongtao-100ask-scada-called-main-pro-clean: called/$(MAKEFILE).main FORCE
	cd called/ && $(MAKE) -f $(MAKEFILE).main clean
sub--home-hongtao-100ask-scada-called-main-pro-distclean: called/$(MAKEFILE).main FORCE
	cd called/ && $(MAKE) -f $(MAKEFILE).main distclean
sub--home-hongtao-100ask-scada-called-main-pro-install_subtargets: called/$(MAKEFILE).main FORCE
	cd called/ && $(MAKE) -f $(MAKEFILE).main install
sub--home-hongtao-100ask-scada-called-main-pro-uninstall_subtargets: called/$(MAKEFILE).main FORCE
	cd called/ && $(MAKE) -f $(MAKEFILE).main uninstall
modules/bd/$(MAKEFILE).mod_bd_sqlite: 
	@$(CHK_DIR_EXISTS) modules/bd/ || $(MKDIR) modules/bd/ 
	cd modules/bd/ && $(QMAKE) /home/hongtao/100ask/scada/modules/bd/mod_bd_sqlite.pro -o $(MAKEFILE).mod_bd_sqlite
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) modules/bd/ || $(MKDIR) modules/bd/ 
	cd modules/bd/ && $(QMAKE) /home/hongtao/100ask/scada/modules/bd/mod_bd_sqlite.pro -o $(MAKEFILE).mod_bd_sqlite
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro: modules/bd/$(MAKEFILE).mod_bd_sqlite FORCE
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-make_default: modules/bd/$(MAKEFILE).mod_bd_sqlite FORCE
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite 
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-make_first: modules/bd/$(MAKEFILE).mod_bd_sqlite FORCE
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite first
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-all: modules/bd/$(MAKEFILE).mod_bd_sqlite FORCE
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite all
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-clean: modules/bd/$(MAKEFILE).mod_bd_sqlite FORCE
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite clean
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-distclean: modules/bd/$(MAKEFILE).mod_bd_sqlite FORCE
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite distclean
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-install_subtargets: modules/bd/$(MAKEFILE).mod_bd_sqlite FORCE
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite install
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-uninstall_subtargets: modules/bd/$(MAKEFILE).mod_bd_sqlite FORCE
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite uninstall
modules/ui/$(MAKEFILE).mod_ui_qtstart: 
	@$(CHK_DIR_EXISTS) modules/ui/ || $(MKDIR) modules/ui/ 
	cd modules/ui/ && $(QMAKE) /home/hongtao/100ask/scada/modules/ui/mod_ui_qtstart.pro -o $(MAKEFILE).mod_ui_qtstart
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) modules/ui/ || $(MKDIR) modules/ui/ 
	cd modules/ui/ && $(QMAKE) /home/hongtao/100ask/scada/modules/ui/mod_ui_qtstart.pro -o $(MAKEFILE).mod_ui_qtstart
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro: modules/ui/$(MAKEFILE).mod_ui_qtstart FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-make_default: modules/ui/$(MAKEFILE).mod_ui_qtstart FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart 
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-make_first: modules/ui/$(MAKEFILE).mod_ui_qtstart FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart first
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-all: modules/ui/$(MAKEFILE).mod_ui_qtstart FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart all
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-clean: modules/ui/$(MAKEFILE).mod_ui_qtstart FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart clean
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-distclean: modules/ui/$(MAKEFILE).mod_ui_qtstart FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart distclean
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-install_subtargets: modules/ui/$(MAKEFILE).mod_ui_qtstart FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart install
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-uninstall_subtargets: modules/ui/$(MAKEFILE).mod_ui_qtstart FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart uninstall
modules/ui/$(MAKEFILE).mod_ui_qtmain: 
	@$(CHK_DIR_EXISTS) modules/ui/ || $(MKDIR) modules/ui/ 
	cd modules/ui/ && $(QMAKE) /home/hongtao/100ask/scada/modules/ui/mod_ui_qtmain.pro -o $(MAKEFILE).mod_ui_qtmain
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) modules/ui/ || $(MKDIR) modules/ui/ 
	cd modules/ui/ && $(QMAKE) /home/hongtao/100ask/scada/modules/ui/mod_ui_qtmain.pro -o $(MAKEFILE).mod_ui_qtmain
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro: modules/ui/$(MAKEFILE).mod_ui_qtmain FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-make_default: modules/ui/$(MAKEFILE).mod_ui_qtmain FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain 
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-make_first: modules/ui/$(MAKEFILE).mod_ui_qtmain FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain first
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-all: modules/ui/$(MAKEFILE).mod_ui_qtmain FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain all
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-clean: modules/ui/$(MAKEFILE).mod_ui_qtmain FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain clean
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-distclean: modules/ui/$(MAKEFILE).mod_ui_qtmain FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain distclean
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-install_subtargets: modules/ui/$(MAKEFILE).mod_ui_qtmain FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain install
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-uninstall_subtargets: modules/ui/$(MAKEFILE).mod_ui_qtmain FORCE
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain uninstall

Makefile: esmu.pro  /usr/local/Trolltech/qt.x86.4.8.6/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/unix.conf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/linux.conf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/qconfig.pri \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/release.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/shared.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/qt.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/moc.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/resources.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/uic.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/lex.prf \
		/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile esmu.pro
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/unix.conf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/linux.conf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/qconfig.pri:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/release.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/default_post.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/shared.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/qt.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/moc.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/resources.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/uic.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/yacc.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/lex.prf:
/usr/local/Trolltech/qt.x86.4.8.6/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile esmu.pro

qmake_all: sub--home-hongtao-100ask-scada-src-scada-pro-qmake_all sub--home-hongtao-100ask-scada-called-main-pro-qmake_all sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-qmake_all sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-qmake_all sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-qmake_all FORCE

make_default: sub--home-hongtao-100ask-scada-src-scada-pro-make_default sub--home-hongtao-100ask-scada-called-main-pro-make_default sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-make_default sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-make_default sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-make_default FORCE
make_first: sub--home-hongtao-100ask-scada-src-scada-pro-make_first sub--home-hongtao-100ask-scada-called-main-pro-make_first sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-make_first sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-make_first sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-make_first FORCE
all: sub--home-hongtao-100ask-scada-src-scada-pro-all sub--home-hongtao-100ask-scada-called-main-pro-all sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-all sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-all sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-all FORCE
clean: sub--home-hongtao-100ask-scada-src-scada-pro-clean sub--home-hongtao-100ask-scada-called-main-pro-clean sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-clean sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-clean sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-clean FORCE
distclean: sub--home-hongtao-100ask-scada-src-scada-pro-distclean sub--home-hongtao-100ask-scada-called-main-pro-distclean sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-distclean sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-distclean sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub--home-hongtao-100ask-scada-src-scada-pro-install_subtargets sub--home-hongtao-100ask-scada-called-main-pro-install_subtargets sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-install_subtargets sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-install_subtargets sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-install_subtargets FORCE
uninstall_subtargets: sub--home-hongtao-100ask-scada-src-scada-pro-uninstall_subtargets sub--home-hongtao-100ask-scada-called-main-pro-uninstall_subtargets sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-uninstall_subtargets sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-uninstall_subtargets sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-uninstall_subtargets FORCE

sub--home-hongtao-100ask-scada-src-scada-pro-check: src/$(MAKEFILE).scada
	cd src/ && $(MAKE) -f $(MAKEFILE).scada check
sub--home-hongtao-100ask-scada-called-main-pro-check: called/$(MAKEFILE).main
	cd called/ && $(MAKE) -f $(MAKEFILE).main check
sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-check: modules/bd/$(MAKEFILE).mod_bd_sqlite
	cd modules/bd/ && $(MAKE) -f $(MAKEFILE).mod_bd_sqlite check
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-check: modules/ui/$(MAKEFILE).mod_ui_qtstart
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtstart check
sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-check: modules/ui/$(MAKEFILE).mod_ui_qtmain
	cd modules/ui/ && $(MAKE) -f $(MAKEFILE).mod_ui_qtmain check
check: sub--home-hongtao-100ask-scada-src-scada-pro-check sub--home-hongtao-100ask-scada-called-main-pro-check sub--home-hongtao-100ask-scada-modules-bd-mod_bd_sqlite-pro-check sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtstart-pro-check sub--home-hongtao-100ask-scada-modules-ui-mod_ui_qtmain-pro-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

